backend/Modules/Accountants/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Accountants\Http\Controllers'], function()
{
	//Route::get('/', 'AccountantsController@index');
	Route::get('accountants/cashFlow','AccountantsController@cashFlow')->name('accountants.cashFlow');
	Route::post('accountants/cashFlow/periode','AccountantsController@cashFlowPeriode')->name('accountants.cashFlowPeriode');
	Route::get('accountants/invoiceList','AccountantsController@invoiceList')->name('accountants.invoiceList');
	Route::get('accountants/destroyAccount/{id}','AccountantsController@destroyAccount')->name('accountants.destroyAccount');

	Route::get('accountants/importPenjualan','AccountantsController@importPenjualan')->name('accountants.importPenjualan');
	Route::post('accountants/uploadPenjualan','AccountantsController@uploadPenjualan')->name('accountants.uploadPenjualan');
	Route::get('accountants/importPembelian','AccountantsController@importPembelian')->name('accountants.importPembelian');
	Route::post('accountants/uploadPembelian','AccountantsController@uploadPembelian')->name('accountants.uploadPembelian');


	Route::resource('accountants','AccountantsController');
});

backend/Modules/Accountants/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Module Accountants</title>
	</head>
	<body>
		@yield('content')
	</body>
</html>

backend/Modules/Accountants/Resources/views/layouts/menu.blade.php
<?php $user = \Sentinel::getUser(); ?>

<?php if($user->hasAccess(['accountants.general'])){ ?>
<li><a><i class="icon-pencil3"></i>Account</a>
	<ul>		
		<li><a href="{{route('accountants.index')}}">Account List</a></li>
		<li><a href="{{route('accountants.create')}}">Add New Account</a></li>
	</ul>
</li>
<?php } ?>
<?php if($user->hasAccess(['accountants.cashFlow'])){ ?>
<li><a href="{{route('accountants.cashFlow')}}"><i class="icon-pencil3"></i>Cash Flow</a></li>
<?php } ?>