backend/Modules/Storage/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Storage\Http\Controllers'], function()
{
	//Route::get('/', 'StorageController@index');
	Route::any('storage/getAllSuppliers','StorageController@getAllSuppliers')->name('storage.getAllSuppliers');

	Route::any('storage/get/customProducts','StorageController@getCustomProducts')->name('storage.getCustomProducts');
	Route::get('storage/searchProductSupplier/{storage_id}/{product_id}','StorageController@searchProductSupplier')->name('storage.searchProductSupplier');
	Route::get('storage/destroyCustomProducts/{id}','StorageController@destroyCustomProducts')->name('storage.destroyCustomProducts');
	Route::get('storage/pagination/{currentPage}','StorageController@pagination')->name('storage.pagination');
	Route::any('storage/searchData','StorageController@searchData')->name('storage.searchData');

	Route::get('storage/importCustomProducts','StorageController@importCustomProducts')->name('storage.importCustomProducts');
	Route::post('storage/uploadCustomProducts','StorageController@uploadCustomProducts')->name('storage.uploadCustomProducts');
	

	Route::get('storage/importSupplier','StorageController@importSupplier')->name('storage.importCustomProducts');
	Route::post('storage/uploadSupplier','StorageController@uploadSupplier')->name('storage.uploadSupplier');
	//Route::get('storage/exportSupplier','StorageController@exportSupplier')->name('storage.exportSupplier');



	Route::get('storage/supplier','StorageController@supplierIndex')->name('storage.supplier');
	Route::get('storage/addSupplier','StorageController@addSupplier')->name('storage.addSupplier');
	Route::post('storage/storeSupplier','StorageController@storeSupplier')->name('storage.storeSupplier');
	Route::get('storage/editSupplier/{id}','StorageController@editSupplier')->name('storage.editSupplier');
	Route::put('storage/{id}/updateSupplier','StorageController@updateSupplier')->name('storage.updateSupplier');
	Route::get('storage/destroySupplier/{id}','StorageController@destroySupplier')->name('storage.destroySupplier');

	Route::get('storage/transactions/{id}','StorageController@transactions')->name('storage.transactions');
	Route::put('storage/{id}/updateTransactions','StorageController@updateTransactions')->name('storage.updateTransactions');
	Route::resource('storage','StorageController');
});

backend/Modules/Storage/Entities/Supplier.php
<?php

namespace Modules\Storage\Entities;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $fillable = [];
    protected $table = 'supplier';

    public function storage(){
    	return $this->hasMany('\Modules\Storage\Entities\Storage','supplier_id');
    }

    public function payable(){
        return $this->hasMany('\Modules\Debts\Entities\Payable','supplier_id');
    }

    public static function saveSupplier($id,$data){
    	\DB::beginTransaction();
    	try {
    		if(is_null($id)){
    			$supplier = new Supplier();
	    	}else{
	    		$supplier = Supplier::find($id);
	    	}

	    	$supplier->name = $data['name'];
	    	$supplier->address = $data['address'];
	    	$supplier->phone = $data['phone'];
	    	$supplier->email = $data['email'];
	    	$supplier->save();
    	} catch (\Exception $e) {
    		\DB::rollback();
    		dd($e->getMessage());
    	}
    	\DB::commit();

		// update activity log
		$current_user = \Sentinel::getUser();
		if(is_null($id)){
			$log = array(
				'desc' => 'Adding new supplier with supplier id: '.$supplier->id.' '
			);
    	}else{
    		$log = array(
				'desc' => 'Editing supplier with supplier id: '.$supplier->id.' '
			);
    	}
		event(new \App\Events\UpdateData($current_user, $log));

    	return $supplier;
    }
}

backend/Modules/Storage/Resources/views/supplier/_form.blade.php
<?php
	use \Illuminate\Support\Facades\Input;
	if(!isset($method)){
		$method = 'post';
	}

?>
<script type="text/javascript" src="<?php echo asset('assets/js/plugins/forms/styling/uniform.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo asset('assets/js/pages/form_layouts.js') ?>"></script>


{{ Form::open(array('action' => $action, 'method' => $method, 'class' => 'form-horizontal')) }}
<fieldset class="content-group">
							<legend class="text-bold"><?php if(isset($supplier)){ echo 'Edit supplier'; }else{ echo 'Create supplier';}?></legend>
								<div class="form-group">
									<label class="control-label col-lg-2">Supplier name</label>
									<div class="col-lg-10">
										{{Form::text('name', isset($supplier->name)?$supplier->name:null, array('class' => 'form-control','required' => 'required'))}}
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-lg-2">Address</label>
									<div class="col-lg-10">
										{{Form::text('address', isset($supplier->address)?$supplier->address:null, array('class' => 'form-control'))}}
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-lg-2">Phone</label>
									<div class="col-lg-10">
										{{Form::text('phone', isset($supplier->phone)?$supplier->phone:null, array('class' => 'form-control'))}}
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-lg-2">Email</label>
									<div class="col-lg-10">
										{{Form::text('email', isset($supplier->email)?$supplier->email:null, array('class' => 'form-control'))}}
									</div>
								</div>
								<div class="text-right">
									<button type="submit" class="btn btn-primary">Submit <i class="icon-arrow-right14 position-right"></i></button>
								</div>
						</fieldset>
{{ Form::close() }}

backend/Modules/Storage/Resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('header')
    @parent
    <!-- JS Extra for form -->
 
	<?php $success_message = session('success'); if($success_message){?>
		<script>
		jQuery(document).ready(function(){
			alert('<?php echo $success_message; ?>');
		});
		</script>
	<?php session()->forget('success'); } ?>


 <style>
 	.clear{clear:both}

 </style>
@endsection
@section('content')
<!-- Page header -->
				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Suppliers</h4>
						</div>
					</div>

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="{{route('dashboard')}}"><i class="icon-home2 position-left"></i> Home</a></li>
							<li><a href="{{route('storage.supplier')}}">Suppliers</a></li>
							<li class="active">Create</li>
						</ul>
					</div>
				</div>
				<!-- /page header -->
				<div class="content">
				<div class="panel panel-flat">
				<div class="panel-body">
					@include('storage::supplier._form', ['action' => '\Modules\Storage\Http\Controllers\StorageController@storeSupplier'])
				</div>
				</div>
				</div>
@endsection

backend/Modules/Storage/Resources/views/supplier/edit.blade.php
@extends('layouts.app')

@section('header')

    @parent
 <style>
 	.clear{clear:both}
 </style>
@endsection

@section('content')
<!-- Page header -->
				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h4><i class="icon-arrow-left52 position-left"></i>Supplier</h4>
						</div>
					</div>

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="{{route('dashboard')}}"><i class="icon-home2 position-left"></i> Home</a></li>
							<li><a href="{{route('storage.supplier')}}">Supplier</a></li>
							<li class="active">edit</li>
						</ul>
					</div>
				</div>
				<!-- /page header -->
				<div class="content">
				<div class="panel panel-flat">
				<div class="panel-body">
					@include('storage::supplier._form', ['action' => array('\Modules\Storage\Http\Controllers\StorageController@updateSupplier', $supplier->id), 'method' => 'PUT'])
				</div>
				</div>
				</div>
@endsection

backend/Modules/Storage/Resources/views/supplier/index.blade.php
@extends('layouts.app')
@section('header')

    @parent
	
	<?php $success_message = session('success'); if($success_message){?>
		<script>
		jQuery(document).ready(function(){
			alert('<?php echo $success_message; ?>');
		});
		</script>
	<?php session()->forget('success'); } ?>
	
	<script>
	jQuery(document).ready(function($){
		$('table.product').on('click','a.remove',function(e){
			// var rewardId = $(this).data('id');
			// $.ajax({
			// 	method: 'get',
			// 	url: '<?php echo route('dashboard'); ?>/eventpoints/eventrewarddestroy/'+rewardId
			// });
			var supplierId = $(this).data('id');
			var confirmation = confirm('Apakah anda yakin ingin melakukan penghapusan produk ini ?');
			if(confirmation == true){
				window.location.replace("{{route('dashboard')}}/storage/destroySupplier/"+supplierId);
			}
		});
	});
	</script>
@endsection
@section('content')
				<!-- Page header -->
				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h4><i class="icon-arrow-left52 position-left"></i>Suppliers</h4>
						</div>
					</div>

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="{{route('dashboard')}}"><i class="icon-home2 position-left"></i> Home</a></li>
							<li class="active">Supplier</li>
						</ul>

					</div>
				</div>
				<!-- /page header -->
				<div class="content">
					<div class="panel panel-flat">
					<table class="table datatable-basic product">
					<thead>
						<tr>
							<th style="text-align:center;">Id</th>
							<th style="text-align:center;">Supplier Name</th>
							<th style="text-align:center;">Supplier Address</th>
							<th style="text-align:center;">Phone</th>
							<th style="text-align:center;">Email</th>
							<th style="text-align:center;">Action</th>
						</tr>
					</thead>
					<tbody>	
						<?php if(isset($suppliers)){ ?>
							<?php foreach($suppliers as $supplier){?>
							<tr>
								<td style="text-align:center;"><?php if($supplier->id){echo $supplier->id;}else{ echo '-';  }?></td>
								<td style="text-align:center;"><?php if($supplier->name){echo $supplier->name;}else{ echo '-';  }?></td>
								<td style="text-align:center;"><?php if($supplier->address){echo $supplier->address;}else{ echo '-';  }?></td>
								<td style="text-align:center;"><?php if($supplier->phone){echo $supplier->phone;}else{ echo '-';  }?></td>
								<td style="text-align:center;"><?php if($supplier->email){echo $supplier->email;}else{ echo '-';  }?></td>
								<td>
									<ul class="icons-list">
										<li >
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">
												<i class="icon-cog7"></i>
												<span class="caret"></span>
											</a>
											<ul class="dropdown-menu dropdown-menu-right">
												<li class="dropdown-header">Options</li>
												<li><a href="{{route('storage.editSupplier',$supplier->id)}}"><i class="icon-pencil7"></i>Edit entry</a></li>
												<li><a class="remove" data-id="<?php echo $supplier->id?>"><i class="icon-pencil7"></i>Delete</a></li>
											</ul>
										</li>
									</ul>
								</td>
							</tr>
							<?php } ?>
						<?php } ?>
					</tbody>
					</table>	
					</div>
				</div>

@endsection

backend/Modules/Storage/Resources/views/supplier/uploadSupplier.blade.php
@extends('layouts.app')

@section('header')
    @parent
    <!-- JS Extra for form -->
 

 <script>
 	jQuery(document).ready(function($){
 		$('html').on('click','a.addMoreSupplier',function(e){
 			var x = $('.supplier .form-group').size();
 			x = x - 1;

 			var html = '<div class="form-group">'+$('.supplier .form-group').html()+'</div>';
 			var re = new RegExp("[x]", 'g');
			htmlModif = html.replace(/\[x\]/g, '['+x+']');
 			

 			$('.supplier').append(htmlModif);
 		});
 	});
 </script>

 <style>
 	.clear{clear:both}

 </style>
@endsection
@section('content')
<!-- Page header -->
				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Custom Products</h4>
						</div>
					</div>

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="{{route('dashboard')}}"><i class="icon-home2 position-left"></i> Home</a></li>
							<li><a href="{{route('storage.index')}}">Supplier</a></li>
							<li class="active">Upload</li>
						</ul>
					</div>
				</div>
				<!-- /page header -->
				<div class="content">
				<div class="panel panel-flat">
				<div class="panel-body">
					{{Form::open(array('method' => 'post', 'action' => '\Modules\Storage\Http\Controllers\StorageController@uploadSupplier', 'enctype' => 'multipart/form-data'))}}
						<div class="form-group">
							<label class="control-label col-lg-2">Upload file</label>
							<div class="col-lg-10">
								<input type="file" name="csv_file">
							</div>
						</div>
						<div class="text-right">
							<button type="submit" class="btn btn-primary">Submit <i class="icon-arrow-right14 position-right"></i></button>
						</div>
					{{Form::close()}}
				</div>
				</div>
				</div>
@endsection